ARG UBUNTU=20.04
FROM wpilib/ubuntu-base:${UBUNTU}

RUN curl https://apt.llvm.org/llvm-snapshot.gpg.key | gpg --dearmor - > /etc/apt/trusted.gpg.d/llvm.gpg && \
    add-apt-repository -n "deb https://apt.llvm.org/focal llvm-toolchain-focal-9 main" && \
    add-apt-repository -n "deb https://apt.llvm.org/focal llvm-toolchain-focal-10 main" && \
    add-apt-repository -n "deb https://apt.llvm.org/focal llvm-toolchain-focal-11 main" && \
    add-apt-repository -n "deb https://apt.llvm.org/focal llvm-toolchain-focal-12 main" && \
    add-apt-repository -n "deb https://apt.llvm.org/focal llvm-toolchain-focal-13 main" && \
    add-apt-repository -n "deb https://apt.llvm.org/focal llvm-toolchain-focal-14 main" && \
    apt-get update && \
    apt-get install -y \
        clang-9 \
        clang-10 \
        clang-11 \
        clang-12 \
        clang-13 \
        clang-14 \
        clang-format-9 \
        clang-format-10 \
        clang-format-11 \
        clang-format-12 \
        clang-format-13 \
        clang-format-14 \
        clangd-9 \
        clangd-10 \
        clangd-11 \
        clangd-12 \
        clangd-13 \
        clangd-14 && \
    rm -rf /var/lib/apt/lists/*

RUN update-alternatives --install /usr/bin/clang clang /usr/bin/clang-9 900 \
        --slave /usr/bin/clang++ clang++ /usr/bin/clang++-9 \
        --slave /usr/bin/clang-format clang-format /usr/bin/clang-format-9 \
        --slave /usr/bin/clangd clangd /usr/bin/clangd-9 && \
    update-alternatives --install /usr/bin/clang clang /usr/bin/clang-10 1000 \
        --slave /usr/bin/clang++ clang++ /usr/bin/clang++-10 \
        --slave /usr/bin/clang-format clang-format /usr/bin/clang-format-10 \
        --slave /usr/bin/clangd clangd /usr/bin/clangd-10 && \
    update-alternatives --install /usr/bin/clang clang /usr/bin/clang-11 1100 \
        --slave /usr/bin/clang++ clang++ /usr/bin/clang++-11 \
        --slave /usr/bin/clang-format clang-format /usr/bin/clang-format-11 \
        --slave /usr/bin/clangd clangd /usr/bin/clangd-11 && \
    update-alternatives --install /usr/bin/clang clang /usr/bin/clang-12 1200 \
        --slave /usr/bin/clang++ clang++ /usr/bin/clang++-12 \
        --slave /usr/bin/clang-format clang-format /usr/bin/clang-format-12 \
        --slave /usr/bin/clangd clangd /usr/bin/clangd-12 && \
    update-alternatives --install /usr/bin/clang clang /usr/bin/clang-13 1300 \
        --slave /usr/bin/clang++ clang++ /usr/bin/clang++-13 \
        --slave /usr/bin/clang-format clang-format /usr/bin/clang-format-13 \
        --slave /usr/bin/clangd clangd /usr/bin/clangd-13 && \
    update-alternatives --install /usr/bin/clang clang /usr/bin/clang-14 1400 \
        --slave /usr/bin/clang++ clang++ /usr/bin/clang++-14 \
        --slave /usr/bin/clang-format clang-format /usr/bin/clang-format-14 \
        --slave /usr/bin/clangd clangd /usr/bin/clangd-14