name: CI

on: [push, pull_request, workflow_dispatch]

jobs:
  build20:
    name: Build-20.04
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: make UBUNTU=20.04 update
      - run: make UBUNTU=20.04 build
      - name: Login to Dockerhub
        uses: docker/login-action@v2
        if: ${{ github.repository_owner == 'wpilibsuite' && github.ref == 'refs/heads/main' }} 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        if: ${{ github.repository_owner == 'wpilibsuite' && github.ref == 'refs/heads/main' }} 
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - run: make UBUNTU=20.04 push
        if: ${{ github.repository_owner == 'wpilibsuite' && github.ref == 'refs/heads/main' }} 
